= Паскал тест 2
include::locale/attributes-bg.adoc[]
:toc: left
:toclevels: 4
:sectnums:
:source-highlighter: coderay
:docinfo1:

ifndef::backend-pdf[]
++++
<style>
body { font-family: "Open Sans", "DejaVu Sans", sans-serif; }
</style>
++++
endif::[]

.Въпрос 1
****
Suppose that _Willy_ and _Nilly_ are _boolean_ variables. What will the value of
Willy be after assignment 1 if _Nilly_ is true? false? Is there anything wrong with
assignment 2 syntactically? From the viewpoint of conciseness or clarity?

[source]
----
Willy := Nilly = false; {Assignment 1}
Willy := Nilly = true;  {Assignment 2}
----

.Answer
[%collapsible]
====
The first assignment statement gives _Willy_ the opposite value of _Nilly_. If _Nilly_
equals _true_, _Willy_ becomes _false_, and if _Nilly_ represents _false_, _Willy_ takes on the
value _true_. The second assignment statement has correct Pascal syntax, but is
redundant. It should have been written as:

[source]
----
Willy := Nilly;
----

because the expression `Nilly=true` is identical to the value of _Nilly_.

====

****

.Въпрос 2
****
Rewrite this assignment as an if ... then ... else statement.

[source]
----
Finished := Response = 'Q';
----

.Answer
[%collapsible]
====

[source]
----
if Response = 'Q'
  then Finished := true
  else Finished := false;
----

====

****

.Въпрос 3
****
What’s wrong with the boolean expression in this statement?

[source]
----
if Finished=true then ...
----

.Answer
[%collapsible]
====
As a _boolean_ variable, _Finished_ represents either the value _true_ or _false_.
`Finished=true` represents the exact same value. Thus, the redundant way the
expression is written forces the computer to go through the unenlightening exercise
of determining that `true=true` is _true_, or that `false=true` is _false_.
====

****

Въпрос 4
****
Write each of these relations or conditions as a _boolean_ expression.

[loweralpha]
a. _ConditionMet_ is _true_
b. 50 ≤ Time ≤ 100
c. Letter is 'V' or _Goals_ is less than 4
d. A < 27, B > 6, C ≠ 13, and _Char_ isn't 'T'
e. A < 21, B > 6, C ≠ 13, and _Char_ isn't 'T' or, on the other hand, 50 ≤ Time ≤ 100
f. _State_ is neither _High_ nor _Low_.

.Answer
[%collapsible]
====
Note the necessary use of parentheses around relational expressions.

[source]
----
a) ConditionMet
b) (Time>=50) and (Time<=100)
c) (Letter='V') or (Goals<4)
d) (A<27) and (B>6) and (C<>13) and (Char<>'T')
e) ((A<27) and (B>6) and (C<>13) and (Char<>'T'))
    or ((Time>=50) and (Time<=100))
f) (State<>High) and (State<>Low)
----

====

****

Въпрос 5
****
Is it possible for this to be a valid expression?

[source]
----
InputValue in [ -15 .. 25, 'f' .. 'w' ]
----

.Answer
[%collapsible]
====
It couldn’t possibly be a good _boolean_ expression, because we’ve tried to define
a set that contains two different types of values -- _integer_, and _char_. The members
of a set, and the value whose membership we’re checking, must all belong to the
same ordinal type.
====

****

Въпрос 6
****
What’s wrong with these exit conditions? Why are they probably in error?

[source]
----
   repeat
     SomeActions
a. until true
b. untilfalse
c. until abs(Counter) < 0
d. until (Value> 10) and (Value<=5)
e. until (Value<=10) or (Value>=11)
----

.Answer
[%collapsible]
====
All these exit conditions are either always _true_ (a, e), or invariably _false_ (b, c,
d). There is no way any of them can be modified. Thus, the `true` loops will only
take place once, and the `false` loops will repeat forever.

====

****

Въпрос 7
****
What is the intention and effect of function _RawPower_, below? What 
restriction _Power_ does it remove?

[source]
----
function RawPower(X: real; n: integer): real;
{Recursively calculates X^n^. Assume?}
begin
  if n = 0
    then RawPower := 1
    else if n > 0
      then RawPower :** X * RawPower(X, n-1)
      else RawPower := 1 / RawPower(X, -n)
end; {RawPower}
----

.Answer
[%collapsible]
====
_RawPower_ is considerably more robust than _Power_. It is still a recursive 
procedure whose algorithm is nearly identical to Power's. However, it can raise X to a
power smaller than 1. In other words, n can be any _integer_, positive, negative, or
zero.

====

****

Въпрос 8
****
What is the largest number of times the innermost *else* will be entered, above?

.Answer
[%collapsible]
====
At most, the call `Power(X, -n)` will occur once.

====

****

Въпрос 9
****
Is this a valid type declaration? Why or why not?

[source]
----
type Letters = ('A', B', 'C', 'D', 'E', F');
----

.Answer
[%collapsible]
====
It’s illegal. 'A', 'B', etc. are not identifiers--they're constant values of type char.
The definition doesn’t conform to Pascal syntax. We could use A, B, C, etc., as
identifiers, but only if we omitted the single quote marks.

====

****

Въпрос 10
****
Though we’ve seen that values of enumerated ordinal types can be used with
any control statement, there are a few pitfalls to beware of. What’s wrong with
these program segments?

[source]
----
// Left-hand
WorkDay := Monday;
while WorkDay <= Sunday do begin
  read(Hours);
  Total := Total + Hours;
  WorkDay := succ(WorkDay)
end;

// Right-hand
WorkDay := Monday;
repeat
  read(Hours);
  Total := Total + Hours;
  WorkDay := succ(WorkDay)
until WorkDay = Sunday;
----

.Answer
[%collapsible]
====
The left-hand program segment tries to use a *while* loop to cycle through the
days of the week. Unfortunately, its exit condition is that _WorkDay_ be greater than
_Sunday_. As far as our program is concerned, there is no day greater than
_Sunday_ -- the program crashes when it tries to give _WorkDay_ the successor to
_Sunday_.
The second segment bends over too far backwards in an attempt to avoid
making the same error. Its exit condition is that _WorkDay_ equal _Sunday_; 
consequently, the number of hours worked on _Sunday_ is never read in.

[source]
----
----

====

****